angular.module("pokemonApp", ['ui.router'])
    .service("pokemonService", PokemonService)
    .service("pokeparadaService", PokeparadaService)
    .service("oponenteService", OponenteService)
    .service("entrenadorService", EntrenadorService)
    .controller("pokemonController", PokemonController)
    .controller("pokeparadaController", PokeparadaController)
    .controller("oponenteController", OponenteController)
    .controller("entrenadorController",EntrenadorController)
    .controller("botonesController", BotonesController)
    .config(routes)